name: Purge Statically Cache
on: [push]
jobs:
  purge:
    runs-on: ubuntu-latest
    steps:
      - name: Purge Cache
        run: |
          curl -X GET "https://api.statically.io/purge/gh/digiitaltools/ads/main/milet.js"
          curl -X GET "https://api.statically.io/purge/gh/digiitaltools/ads@main/milet.js"
