name: Purge Statically Cache
on:
  push:
    paths:
      - 'milet.js'
      - 'redirect.json'

jobs:
  purge:
    runs-on: ubuntu-latest
    steps:
      - name: Purge Cache by Requesting Files
        run: |
          # Melakukan request ke URL lama dan URL baru untuk memicu refresh cache
          curl -I "https://cdn.statically.io/gh/digiitaltools/ads/main/milet.js"
          curl -I "https://cdn.statically.io/gh/digiitaltools/ads@main/milet.js"
          
          echo "Pemicu pembaruan cache Statically berhasil dikirim."
