name: Purge Statically Cache

on:
  push:
    paths:
      - 'milet.js'
      - 'redirect.json'

jobs:
  purge:
    runs-on: ubuntu-latest
    steps:
      - name: Purge Statically
        run: |
          # Perintah ini memberitahu Statically untuk mengambil versi terbaru
          curl -I "https://cdn.statically.io/screenshot/gh/digiitaltools/ads/main/milet.js"
          curl -I "https://cdn.statically.io/gh/digiitaltools/ads@main/milet.js"
          echo "Cache telah diperbarui untuk Statically"
